name: PR Destroy Environment

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  destroy-dynamic-environment:
    name: Destroy Dynamic Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Trigger dynamic environment destruction
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        shell: bash
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --jobName "Destroy PR Dynamic Environment" \
            --infraRepoName "$(echo ${{ github.repository }} | cut -d'/' -f2)" \
            --releaseVersion "main" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ github.event.number }}" \
            --targetComponent "branch" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --terraformAction "destroy"

  sandbox-tear-down:
    name: Destroy Sandbox Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Trigger sandbox environment destruction
        shell: bash
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --jobName "Sandbox tear down" \
            --infraRepoName "nhs-notify-web-template-management" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ github.event.number }}" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --targetComponent "sandbox" \
            --terraformAction "destroy"
